baseURL = "https://fizzy-spark.github.io/My-Portfolio/"
languageCode = "en-us"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	mainSections = ["posts"]
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true

canonifyURLs = true
relativeURLs = true

#Main Menu Tags

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 3

[[menu.main]]
name = "Search"
url = "/search/"
weight = 4

